<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="acceuille.css" />
	<title>Projet2</title>
</head>
<body>
	<header>
		<nav>
			<li>
		<a href="acceuille.html"><li> ACCEUIL </li></a>
		<a href="inscription.php"><li> SINSCRIRE </li></a>
		<a href="authentification.php"><li> SAUTHENNTIFIER </li></a>
		 
		<a href="voter.php"><li> VOTER </li></a>
		 
	


		<a href="consultervote.php"><li> CONSULTER <br> VOTRE VOTE </li></a>
		<a href=><li> AFFICHER RESULTATS ELECTIONS </li></a>
		<a href="deconnexion.php"><li> DECONNEXION </li></a>

</li>
</nav>
<img src="a.PNG" alt="logo">
	<div>
	<p>République Tunisienne</p> 
	</div>
	</header>
<hr>
<div id="a">
<img src="b.JPG" alt="">
</div>
<div id="b">
<img src="b.JPG" alt="">
</div>
<div id="c">
	<img src="b.JPG" alt="">
</div>

<div id="description">
	<p><h2> description </h2><br><br>Ceci est un site d'èlection fictive online,permetant à des électeures anonymes d'élire les membres du parlement . Un électeur pourra à tout moment retirer son vote ou le modifier. Il poura aussi à tout moment afficher les resultat instantanées des élections qui prennene en compte touts les électeurs sur web.</p>




</body>
<footer>
	<hr>
<div id="suiv">
	<a href="https://www.facebook.com/isietn/"><h2>SUIVEZ NOUS</h2></a>
	<img src="fb.JPG" alt="">
</div>
<div class="center">
	<h2>PHOTOS DE LA CHAMBRE DES <br> REPRESENTANTS</h2>
<span id="image1">
<img src="m.JFIF" alt="">
</span>
<span id="image2">
<img src="ma.PNG" alt="">
</span>

</div>
<div class="end">
	<h2>LIENS_UTILES</h2>
	<a href="">instance supérieure indépendante des élections</a><br>
	<a href="">Chambre des représentants du peuples</a>
</div>
	
</footer>
</html>