<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="consultervote.css" />
	<title>Projet2</title>
</head>
<body>
	<header>
		<nav>
			<li>
		<a href="acceuille.phtml"><li> ACCEUIL </li></a>
		<a href="inscription.php"><li> SINSCRIRE </li></a>
		<a href="authentification.php"><li> SAUTHENNTIFIER </li></a>
		<a href="voter.php"><li> VOTER </li></a>
		<a href="consultervote.php"><li> CONSULTER <br> VOTRE VOTE </li></a>
		<a href=><li> AFFICHER RESULTATS ELECTIONS </li></a>
		<a href="deconnexion.php"><li> DECONNEXION </li></a>

</li>
</nav>
<img src="a.PNG" alt="logo">
	<div>
	<p>République Tunisienne</p> 
	</div>
	</header>
<hr>
<div id="a">
<img src="b.JPG" alt="">
</div>
<div id="b">
<img src="b.JPG" alt="">
</div>
<div id="c">
	<img src="b.JPG" alt="">
</div>


<form method="post">

	<div id="description">
	<p><h2> <?php echo "$pseudo vous avez vote pour le parti $nomParti dans le gouvernorat de $nomGouvernorat."; ?></h2><br><br></p>

<input class="bouton" type="submit" name="supprimer" value="supprimer ce vote"/>

</form>
</body>
<footer>
	<hr>
<div id="suiv">
	<a href="https://www.facebook.com/isietn/"><h2>SUIVEZ NOUS</h2></a>
	<img src="fb.JPG" alt="">
</div>
<div class="center">
	<h2>PHOTOS DE LA CHAMBRE DES <br> REPRESENTANTS</h2>
<span id="image1">
<img src="m.JFIF" alt="">
</span>
<span id="image2">
<img src="ma.PNG" alt="">
</span>

</div>
<div class="end">
	<h2>LIENS_UTILES</h2>
	<a href="">instance supérieure indépendante des élections</a><br>
	<a href="">Chambre des représentants du peuples</a>
</div>
	
</footer>
</html>